defmodule Blitzkeys.TextGenerator do
  @moduledoc """
  Generates typing test text based on language and difficulty settings.

  Supports:
  - Multiple languages (English, Spanish, German, etc.)
  - Different difficulty levels (common words, quotes, code)
  - Customizable text length
  """

  @doc """
  Generates text for a typing game based on settings.
  Returns a list of words for word-by-word validation.

  ## Examples

      iex> Blitzkeys.TextGenerator.generate(%{language: :english, difficulty: :common_words})
      ["the", "quick", "brown", "fox", ...]
  """
  def generate(settings \\ %{}) do
    language = settings[:language] || :english
    difficulty = settings[:difficulty] || :common_words
    word_count = settings[:word_count] || 200

    language
    |> get_word_list(difficulty)
    |> Enum.take_random(word_count)
  end

  # Word lists by language and difficulty

  defp get_word_list(:english, :common_words) do
    [
      "the",
      "be",
      "to",
      "of",
      "and",
      "a",
      "in",
      "that",
      "have",
      "I",
      "it",
      "for",
      "not",
      "on",
      "with",
      "he",
      "as",
      "you",
      "do",
      "at",
      "this",
      "but",
      "his",
      "by",
      "from",
      "they",
      "we",
      "say",
      "her",
      "she",
      "or",
      "an",
      "will",
      "my",
      "one",
      "all",
      "would",
      "there",
      "their",
      "what",
      "so",
      "up",
      "out",
      "if",
      "about",
      "who",
      "get",
      "which",
      "go",
      "me",
      "when",
      "make",
      "can",
      "like",
      "time",
      "no",
      "just",
      "him",
      "know",
      "take",
      "people",
      "into",
      "year",
      "your",
      "good",
      "some",
      "could",
      "them",
      "see",
      "other",
      "than",
      "then",
      "now",
      "look",
      "only",
      "come",
      "its",
      "over",
      "think",
      "also",
      "back",
      "after",
      "use",
      "two",
      "how",
      "our",
      "work",
      "first",
      "well",
      "way",
      "even",
      "new",
      "want",
      "because",
      "any",
      "these",
      "give",
      "day",
      "most",
      "us",
      "world",
      "very",
      "own",
      "here",
      "still",
      "should",
      "might",
      "much",
      "find",
      "between",
      "through",
      "both",
      "life",
      "under",
      "place",
      "where",
      "after",
      "back",
      "little",
      "only",
      "round",
      "man",
      "year",
      "came",
      "show",
      "every",
      "good",
      "give",
      "our",
      "under",
      "name",
      "very",
      "through",
      "just",
      "form",
      "sentence",
      "great",
      "think",
      "say",
      "help",
      "low",
      "line",
      "differ",
      "turn",
      "cause",
      "much",
      "mean",
      "before",
      "move",
      "right"
    ]
  end

  defp get_word_list(:english, :quotes) do
    quotes = [
      "To be or not to be that is the question",
      "The only way to do great work is to love what you do",
      "In the middle of difficulty lies opportunity",
      "The future belongs to those who believe in the beauty of their dreams",
      "It does not matter how slowly you go as long as you do not stop",
      "Everything you can imagine is real",
      "The best time to plant a tree was twenty years ago The second best time is now",
      "Success is not final failure is not fatal it is the courage to continue that counts",
      "Believe you can and you are halfway there",
      "The only impossible journey is the one you never begin"
    ]

    quotes
    |> Enum.random()
    |> String.downcase()
    |> String.split()
  end

  defp get_word_list(:english, :code) do
    [
      "function",
      "return",
      "const",
      "let",
      "var",
      "if",
      "else",
      "for",
      "while",
      "class",
      "import",
      "export",
      "default",
      "async",
      "await",
      "try",
      "catch",
      "throw",
      "new",
      "this",
      "true",
      "false",
      "null",
      "undefined",
      "typeof",
      "instanceof",
      "delete",
      "void",
      "yield",
      "break",
      "continue",
      "switch",
      "case",
      "do",
      "in",
      "of",
      "extends",
      "super",
      "static",
      "public",
      "private",
      "protected",
      "interface",
      "implements",
      "enum",
      "type",
      "namespace",
      "module",
      "package",
      "import",
      "from",
      "as",
      "get",
      "set",
      "debugger",
      "with",
      "arguments"
    ]
  end

  defp get_word_list(:spanish, :common_words) do
    [
      "el",
      "la",
      "de",
      "que",
      "y",
      "a",
      "en",
      "un",
      "ser",
      "se",
      "no",
      "haber",
      "por",
      "con",
      "su",
      "para",
      "como",
      "estar",
      "tener",
      "le",
      "lo",
      "todo",
      "pero",
      "más",
      "hacer",
      "o",
      "poder",
      "decir",
      "este",
      "ir",
      "otro",
      "ese",
      "si",
      "me",
      "ya",
      "ver",
      "porque",
      "dar",
      "cuando",
      "él",
      "muy",
      "sin",
      "vez",
      "mucho",
      "saber",
      "qué",
      "sobre",
      "mi",
      "alguno",
      "mismo",
      "yo",
      "también",
      "hasta",
      "año",
      "dos",
      "querer",
      "entre",
      "así",
      "primero",
      "desde",
      "grande",
      "eso",
      "ni",
      "nos",
      "llegar",
      "pasar",
      "tiempo",
      "ella",
      "sí",
      "día",
      "uno",
      "bien",
      "poco",
      "deber",
      "entonces",
      "poner",
      "cosa",
      "tanto",
      "hombre",
      "parecer",
      "nuestro",
      "tan",
      "donde",
      "ahora",
      "parte",
      "después",
      "vida",
      "quedar",
      "siempre",
      "creer",
      "hablar",
      "llevar",
      "dejar",
      "nada",
      "cada",
      "seguir",
      "menos",
      "nuevo",
      "encontrar",
      "algo"
    ]
  end

  defp get_word_list(:german, :common_words) do
    [
      "der",
      "die",
      "und",
      "in",
      "den",
      "von",
      "zu",
      "das",
      "mit",
      "sich",
      "des",
      "auf",
      "für",
      "ist",
      "im",
      "dem",
      "nicht",
      "ein",
      "eine",
      "als",
      "auch",
      "es",
      "an",
      "werden",
      "aus",
      "er",
      "hat",
      "dass",
      "sie",
      "nach",
      "wird",
      "bei",
      "einer",
      "um",
      "am",
      "sind",
      "noch",
      "wie",
      "einem",
      "über",
      "einen",
      "so",
      "zum",
      "war",
      "haben",
      "nur",
      "oder",
      "aber",
      "vor",
      "zur",
      "bis",
      "mehr",
      "durch",
      "man",
      "sein",
      "wurde",
      "sei",
      "in",
      "prozent",
      "hatte",
      "kann",
      "gegen",
      "vom",
      "können",
      "schon",
      "wenn",
      "habe",
      "seine",
      "mark",
      "ihre",
      "dann",
      "unter",
      "wir",
      "soll",
      "ich",
      "eines",
      "es",
      "jahr",
      "zwei",
      "diese",
      "dieser",
      "wieder",
      "keine",
      "seinem",
      "ob",
      "ihm",
      "seine",
      "hier",
      "gibt",
      "alle"
    ]
  end

  defp get_word_list(_language, _difficulty) do
    # Fallback to English common words
    get_word_list(:english, :common_words)
  end

  @doc """
  Returns available languages.
  """
  def available_languages do
    [:english, :spanish, :german]
  end

  @doc """
  Returns available difficulty levels.
  """
  def available_difficulties do
    [:common_words, :quotes, :code]
  end
end
